### ISSUE TITLE
Updating to use latest play services how-to ?

### ISSUE THREAD

**Issue by roysinclair** [1dir1/admobrewarded#2]
First off thank you for providing this solution to as it works great.
Please would you be so kind as to advise on how-to update to the latest play services.
At the moment when updating to 11.0.4

The following message is received when trying to load the instance of this module:

[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[INFO] :   art: Rejecting re-init on previously-failed class java.lang.Class<net.birdirbir.admobrewarded.RewardedVideoProxy>
[WARN] :   W/System.err: java.lang.NoClassDefFoundError: net.birdirbir.admobrewarded.RewardedVideoProxy
[WARN] :   W/System.err: 	at net.birdirbir.admobrewarded.AdmobrewardedModule.createAd(AdmobrewardedModule.java:69)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:196)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:243)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.loadActivityScript(TiLaunchActivity.java:128)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.windowCreated(TiLaunchActivity.java:183)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiRootActivity.windowCreated(TiRootActivity.java:172)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:684)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.onCreate(TiLaunchActivity.java:169)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.TiRootActivity.onCreate(TiRootActivity.java:161)
[WARN] :   W/System.err: 	at android.app.Activity.performCreate(Activity.java:5933)
[WARN] :   W/System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
[WARN] :   W/System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
[WARN] :   W/System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
[WARN] :   W/System.err: 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
[WARN] :   W/System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:135)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5221)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
[ERROR] :  TiExceptionHandler: (main) [4,68] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,68] - In /app.js:256,30
[ERROR] :  TiExceptionHandler: (main) [0,68] - Message: Uncaught net.birdirbir.admobrewarded.RewardedVideoProxy
[ERROR] :  TiExceptionHandler: (main) [0,68] - Source: var instance = admobrewarded.createAd({
[ERROR] :  V8Exception: Exception occurred at /app.js:256: Uncaught net.birdirbir.admobrewarded.RewardedVideoProxy
[ERROR] :  V8Exception: net.birdirbir.admobrewarded.RewardedVideoProxy

We are trying to us this module with ti.goosh however it is causing an issue due to the updated play services jar's

Thank you so much for your help

**Comment by canbican** [comment]
Sorry for replying so late. I wasn't into it for a while. I can't give you a solution but do you need to upgrade it anyway?

Closing it because I'm so late at replying, not because it's solved. If you care to reply about a solution, please feel free to repoen it.
